-- ============================================
-- CivicLens Supabase Database Schema
-- Run this SQL in your Supabase SQL Editor
-- ============================================

-- 1. Create Users Table
CREATE TABLE IF NOT EXISTS public.users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  email TEXT UNIQUE NOT NULL,
  password_hash TEXT NOT NULL,
  role TEXT DEFAULT 'user' CHECK (role IN ('user', 'admin')),
  created_at TIMESTAMPTZ DEFAULT TIMEZONE('utc', NOW()) NOT NULL
);

-- 2. Create Complaints Table
CREATE TABLE IF NOT EXISTS public.complaints (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tracking_id TEXT UNIQUE NOT NULL,
  user_id BIGINT REFERENCES public.users(id) ON DELETE CASCADE NOT NULL,
  title TEXT,
  description TEXT NOT NULL,
  category TEXT DEFAULT 'General',
  classification_result TEXT,
  image_url TEXT,
  latitude DOUBLE PRECISION NOT NULL,
  longitude DOUBLE PRECISION NOT NULL,
  status TEXT DEFAULT 'Pending' CHECK (status IN ('Pending', 'In-Review', 'Resolved')),
  created_at TIMESTAMPTZ DEFAULT TIMEZONE('utc', NOW()) NOT NULL,
  updated_at TIMESTAMPTZ DEFAULT TIMEZONE('utc', NOW()) NOT NULL
);

-- 3. Create Admin Logs Table
CREATE TABLE IF NOT EXISTS public.admin_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  complaint_id BIGINT REFERENCES public.complaints(id) ON DELETE CASCADE NOT NULL,
  admin_id BIGINT REFERENCES public.users(id) ON DELETE CASCADE NOT NULL,
  message TEXT NOT NULL,
  timestamp TIMESTAMPTZ DEFAULT TIMEZONE('utc', NOW()) NOT NULL
);

-- 4. Create Indexes for faster queries
CREATE INDEX IF NOT EXISTS idx_complaints_tracking_id ON public.complaints(tracking_id);
CREATE INDEX IF NOT EXISTS idx_complaints_user_id ON public.complaints(user_id);
CREATE INDEX IF NOT EXISTS idx_complaints_status ON public.complaints(status);
CREATE INDEX IF NOT EXISTS idx_admin_logs_complaint_id ON public.admin_logs(complaint_id);

-- 5. Enable Row Level Security (RLS)
ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.complaints ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.admin_logs ENABLE ROW LEVEL SECURITY;

-- 6. RLS Policies (Allow all for now - customize for production)
CREATE POLICY "Allow all operations on users" ON public.users FOR ALL USING (true);
CREATE POLICY "Allow all operations on complaints" ON public.complaints FOR ALL USING (true);
CREATE POLICY "Allow all operations on admin_logs" ON public.admin_logs FOR ALL USING (true);

-- ============================================
-- STORAGE BUCKET SETUP (Do this manually in Supabase Dashboard)
-- ============================================
-- 1. Go to Storage in Supabase Dashboard
-- 2. Create a new bucket named: complaint-images
-- 3. Make it PUBLIC
-- 4. Set file size limit as needed (e.g., 5MB)

-- ============================================
-- DEFAULT TEST ACCOUNTS
-- ============================================
-- Run these AFTER creating the tables
-- Password for both: password123 (bcrypt hash below)

-- Admin Account
INSERT INTO public.users (name, email, password_hash, role)
VALUES ('Admin User', 'admin@civiclens.com', '$2b$12$LQv3c1yqBWVHxkd0LHAkCOYz6TtxMQJqhN8/X4.VttYFHeM.t5pLe', 'admin')
ON CONFLICT (email) DO NOTHING;

-- Regular User Account
INSERT INTO public.users (name, email, password_hash, role)
VALUES ('Test User', 'user@civiclens.com', '$2b$12$LQv3c1yqBWVHxkd0LHAkCOYz6TtxMQJqhN8/X4.VttYFHeM.t5pLe', 'user')
ON CONFLICT (email) DO NOTHING;

-- ============================================
-- MIGRATION: Add classification_result column
-- Run this if you already have the table
-- ============================================
ALTER TABLE public.complaints ADD COLUMN IF NOT EXISTS classification_result TEXT;

-- ============================================
-- MIGRATION: Add work completion verification columns
-- Run this to enable before/after image comparison
-- ============================================
ALTER TABLE public.complaints ADD COLUMN IF NOT EXISTS after_image_url TEXT;
ALTER TABLE public.complaints ADD COLUMN IF NOT EXISTS verification_confidence DOUBLE PRECISION;
ALTER TABLE public.complaints ADD COLUMN IF NOT EXISTS verified_at TIMESTAMPTZ;
ALTER TABLE public.complaints ADD COLUMN IF NOT EXISTS verified_by BIGINT REFERENCES public.users(id) ON DELETE SET NULL;

-- ============================================
-- TEST DATA (Optional)
-- ============================================
-- Sample complaint for testing
-- INSERT INTO public.complaints (tracking_id, user_id, title, description, category, latitude, longitude, status)
-- SELECT 'CVC-0001-2025', id, 'Pothole on Main Street', 'Large pothole causing traffic issues', 'Road Damage', 12.9716, 77.5946, 'Pending'
-- FROM public.users WHERE email = 'user@civiclens.com';
